### ISSUE TITLE
new install issue

### ISSUE THREAD

**Issue by sunatthegilddotcom** [Nutlope/roomGPT#12]
run into error in local mode  

SyntaxError: Unexpected token '?'

I have filled .example.env
and also created a rootgpt.env 
with correct replicate token.    But I run into the following error.  Can you please let me know how to fix this issue?

Thank you very much in advance!

npm run dev

> dev
> next dev

/home/abc/roomGPT/node_modules/next/dist/cli/next-dev.js:344
            showAll: args["--show-all"] ?? false,
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.dev (/home/abc/roomGPT/node_modules/next/dist/lib/commands.js:10:30)
    at Object.<anonymous> (/home/abc/roomGPT/node_modules/next/dist/bin/next:141:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

**Comment by d4rkc0de** [comment]
You are probably using an old version of npm, try to upgrade your version:

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

Restart the terminal then rerun the command: npm run dev

**Comment by sunatthegilddotcom** [comment]
Thank you very much for your help @d4rkc0de !   You are right.  The commands above did the trick.   You have a nice day!
