### ISSUE TITLE
generated AI images are not displaying on screen back

### ISSUE THREAD

**Issue by homeez-in** [Nutlope/roomGPT#53]
After uploading the image the generated image is not displayed on screen.

deployed url: https://roomgpt-theta.vercel.app/dream 

issue: after uploading, images are generated in replicate but it is not displayed back on the screen

**error log from chrome developer tool:**
_vercel/insights/script.js:1          Failed to load resource: the server responded with a status of 404 ()
api/generate:1          Failed to load resource: the server responded with a status of 504 ()
dream:1 Uncaught (in promise) SyntaxError: Unexpected token 'A', "An error o"... is not valid JSON

**in vercel log i see this error:**

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at handler (/var/task/.next/server/pages/api/generate.js:124:84)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:488:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:751:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:253:36)
    at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:384:29)
    at async NextNodeServer.handleRequest (/var/task/node_modules/next/dist/server/base-server.js:322:20)
    at async module.exports (/var/task/___next_launcher.cjs:29:9)

**Comment by hhouaiss** [comment]
Hi, did resolve this issue ? i have the same

**Comment by alexbuce** [comment]
i have not done anything specific. saw this quite some time and now it got resolved automatically.. some time image generation took time in replicate i believe...

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
