### ISSUE TITLE
 TypeError [ERR_INVALID_URL]: Invalid URL     at new NodeError (node:internal/errors:399:5)     at URL.onParseError (node:internal/url:566:9)     at new URL (node:internal/url:646:5)     at parseUrl (E:\Fiverr\roomGPT\node_modules\.pnpm\next-auth@4.20.1_next@13.3.0_react-dom@18.2.0_react@18.2.0\node_modules\next-auth\utils\parse-url.js:17:16)     at Object.<anonymous> (E:\Fiverr\roomGPT\node_modules\.pnpm\next-auth@4.20.1_next@13.3.0_react-dom@18.2.0_react@18.2.0\node_modules\next-auth\react\index.js:

### ISSUE THREAD

**Issue by tarifalhasan** [Nutlope/roomGPT#62]
face this error

**Comment by tarifalhasan** [comment]
face this error  TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at URL.onParseError (node:internal/url:566:9)
    at new URL (node:internal/url:646:5)
    at parseUrl (E:\Fiverr\roomGPT\node_modules\.pnpm\next-auth@4.20.1_next@13.3.0_react-dom@18.2.0_react@18.2.0\node_modules\next-auth\utils\parse-url.js:17:16)
    at Object.<anonymous> (E:\Fiverr\roomGPT\node_modules\.pnpm\next-auth@4.20.1_next@13.3.0_react-dom@18.2.0_react@18.2.0\node_modules\next-auth\react\index.js:

**Comment by Godspraisemomoh** [comment]
the issue is with .env file 
NEXTAUTH_URL=

**Comment by tara-singh-danu** [comment]
Facing the same issue when using msw for jest

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
