### ISSUE TITLE
Image uploaded and sent to replicate not appearing on front-end

### ISSUE THREAD

**Issue by boss2256** [Nutlope/roomGPT#73]
![generate ts](https://user-images.githubusercontent.com/72273305/233453028-e94bc790-8fb3-417d-9c30-bda4dec9f51c.png)
![replicaete](https://user-images.githubusercontent.com/72273305/233453036-2fd1dd9b-16cf-498c-98f9-68ed2fe0fb54.png)
![problem](https://user-images.githubusercontent.com/72273305/233453038-41a010ba-1f10-40c9-ae4a-e6a3781502eb.png)
![error](https://user-images.githubusercontent.com/72273305/233453043-1cdce808-15ef-41b1-b664-fabccc10641a.png)
After uploading my photo for replicate API to do its work, it only appeared serverside and i can only see the photo on replicate but it's not being parsed to the front-end client to view.

**Comment by boss2256** [comment]
Could it be because of the new model Nutolope merged from the pull request?

**Comment by boss2256** [comment]
it seems to 
![localhost](https://user-images.githubusercontent.com/72273305/233475259-d4d2b94f-0fbd-498f-a106-6025f8a6e099.png)
only be appearing in localhost

**Comment by PopAI33** [comment]
did you solved this? im havving the same issue

**Comment by R3P-tech** [comment]
There's something with the new model, I have the same POST Issue and, also this GET issue:

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at handler (/var/task/.next/server/pages/api/generate.js:124:84)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:488:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:751:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:253:36)
    at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:384:29)
    at async NextNodeServer.handleRequest (/var/task/node_modules/next/dist/server/base-server.js:322:20)
    at async module.exports (/var/task/___next_launcher.cjs:29:9)

<img width="1214" alt="Capture d’écran 2023-04-24 à 02 48 30" src="https://user-images.githubusercontent.com/130335349/233861897-69492f1f-b6aa-4660-8703-fda8d4655e40.png">

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
