### ISSUE TITLE
Cannot generate images after buying credits

### ISSUE THREAD

**Issue by retrovisor** [Nutlope/roomGPT#83]
Hi everyone, 

So after integrating with my own Stripe keys I was able to buy credits. But then I can't generate any images with this user that has purchased credits. It works normally for trial users, but for the one I bought credits for I get this error:

TypeError: Cannot read properties of undefined (reading 'get')
    at handler (/var/task/.next/server/pages/api/generate.js:154:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:488:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:751:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:253:36)
    at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:384:29)
    at async NextNodeServer.handleRequest (/var/task/node_modules/next/dist/server/base-server.js:322:20)
    at async module.exports (/var/task/___next_launcher.cjs:30:9)
    at async Server.handler (/var/task/___vc/__launcher.js:4925:16)

Any clues on what could be the issue here?

Thanks!

**Comment by Nutlope** [comment]
Hey all. I've just simplified the repo to remove auth and payments so you can clone and deploy very easily, only with a Replicate environment variable. Try it out and if you still have any problems, please open a new issue and I will take a look!
